export const ADD_RESULT = "ADD_RESULT"
export const UPDATE_RESULT = "UPDATE_RESULT"
export const DELETE_RESULT  = "DELETE_RESULT"

export const ADD_PART2_DATA = "ADD_PART2_DATA"
export const UPDATE_PART2_DATA = "UPDATE_PART2_DATA"
export const DELETE_PART2_DATA = "DELETE_PART2_DATA"


export const ADD_PART3_DATA = "ADD_PART3_DATA"
export const UPDATE_PART3_DATA = "UPDATE_PART3_DATA"
export const DELETE_PART3_DATA = "DELETE_PART3_DATA"

export const LOGOUT = "LOGOUT"

export const FORM_DATA="FORM_DATA"